"""
medical_sandbox.py — BioGemma-Guard Secure Code Execution Sandbox
=================================================================

Provides a safe, isolated execution environment for medical calculations
generated by the LLM (e.g. drug dosages, clinical scores like GCS or
NEWS2).

Architecture
------------
When BioGemma-Guard produces a completion containing a Python code block
(typically inside markdown fences), this module:

1. **Extracts** the code from the markdown via regex.
2. **Executes** it in a separate Python subprocess with a strict
   timeout to prevent infinite loops or resource exhaustion.
3. **Captures** stdout, stderr, and the return code into an immutable
   ``SandboxResult`` dataclass.
4. **Verifies** whether the output contains the expected clinical
   value (integration point with the GRPO reward function).

Security Model
--------------
- Each execution runs in a **fresh subprocess** (``sys.executable -c``)
  with no shared state, file handles, or network access to the parent.
- A configurable **timeout** (default 3 s) kills any runaway process.
- An optional **import whitelist** restricts which modules the code
  may use (``math``, ``decimal``, ``statistics``, ``datetime``,
  ``fractions`` by default).

Integration
-----------
>>> from src.inference.medical_sandbox import MedicalCodeSandbox
>>>
>>> sandbox = MedicalCodeSandbox()
>>> code = sandbox.extract_code(llm_completion)
>>> result = sandbox.execute(code)
>>> if sandbox.verify_output(result, expected_value="250.0"):
...     reward += SANDBOX_BONUS

Author : BioGemma-Guard Team
License: Apache-2.0
"""

from __future__ import annotations

import re
import subprocess
import sys
import time
from dataclasses import dataclass
from typing import Sequence


# ──────────────────────────────────────────────────────────────────────
# 1.  RESULT DATACLASS
# ──────────────────────────────────────────────────────────────────────

@dataclass(frozen=True, slots=True)
class SandboxResult:
    """Immutable result of a sandboxed code execution.

    Attributes
    ----------
    success : bool
        ``True`` if the process exited with return code 0 and produced
        no stderr output.
    output : str
        Captured stdout (stripped of leading/trailing whitespace).
    error : str
        Captured stderr (stripped).  Empty string on success.
    execution_time : float
        Wall-clock time in seconds.
    timed_out : bool
        ``True`` if the process was killed due to timeout.
    return_code : int
        Process exit code (``-1`` if timed out before exit).
    """
    success: bool
    output: str
    error: str
    execution_time: float
    timed_out: bool = False
    return_code: int = 0

    def __repr__(self) -> str:  # noqa: D105
        status = "✅ OK" if self.success else ("⏰ TIMEOUT" if self.timed_out else "❌ ERROR")
        preview = self.output[:60] + ("…" if len(self.output) > 60 else "")
        return (
            f"SandboxResult({status}, "
            f"output={preview!r}, "
            f"time={self.execution_time:.3f}s)"
        )


# ──────────────────────────────────────────────────────────────────────
# 2.  CODE EXTRACTION PATTERNS
# ──────────────────────────────────────────────────────────────────────

# Match ```python ... ``` or ``` ... ``` fenced code blocks.
_CODE_BLOCK_RE: re.Pattern = re.compile(
    r"```(?:python|py)?\s*\n(.*?)```",
    flags=re.DOTALL | re.IGNORECASE,
)

# ──────────────────────────────────────────────────────────────────────
# 3.  IMPORT WHITELIST (safe numeric / clinical modules only)
# ──────────────────────────────────────────────────────────────────────

DEFAULT_ALLOWED_IMPORTS: frozenset[str] = frozenset({
    "math",
    "decimal",
    "statistics",
    "datetime",
    "fractions",
    "collections",
    "functools",
    "itertools",
    "numbers",
    "re",
})

# Regex to find `import X` and `from X import ...` statements.
_IMPORT_RE: re.Pattern = re.compile(
    r"^\s*(?:import\s+([\w.]+)|from\s+([\w.]+)\s+import)",
    flags=re.MULTILINE,
)


# ──────────────────────────────────────────────────────────────────────
# 4.  SANDBOX CLASS
# ──────────────────────────────────────────────────────────────────────

class MedicalCodeSandbox:
    """Secure subprocess-based sandbox for medical code execution.

    Parameters
    ----------
    allowed_imports : Sequence[str] | None
        Whitelist of top-level module names the code is permitted to
        import.  Set to ``None`` to disable import checking (not
        recommended in production).
    default_timeout : int
        Default execution timeout in seconds.

    Examples
    --------
    >>> sandbox = MedicalCodeSandbox()
    >>> code = sandbox.extract_code(completion)
    >>> result = sandbox.execute(code, timeout=3)
    >>> result.success
    True
    """

    def __init__(
        self,
        allowed_imports: Sequence[str] | None = None,
        default_timeout: int = 3,
    ) -> None:
        if allowed_imports is None:
            self._allowed: frozenset[str] = DEFAULT_ALLOWED_IMPORTS
        else:
            self._allowed = frozenset(allowed_imports)
        self._default_timeout: int = default_timeout

    # ── code extraction ─────────────────────────────────────────────

    @staticmethod
    def extract_code(completion: str) -> str:
        """Extract Python code from a markdown-fenced code block.

        Searches for the first occurrence of a fenced block
        (````python`` or bare ``````) and returns its content.

        Parameters
        ----------
        completion : str
            Raw LLM completion text potentially containing markdown
            code fences.

        Returns
        -------
        str
            The extracted code, stripped of surrounding whitespace.
            Returns an empty string if no code block is found.

        Examples
        --------
        >>> MedicalCodeSandbox.extract_code(
        ...     "Here is the calculation:\\n```python\\nprint(2+2)\\n```"
        ... )
        'print(2+2)'
        """
        match = _CODE_BLOCK_RE.search(completion)
        if match:
            return match.group(1).strip()
        return ""

    # ── import validation ───────────────────────────────────────────

    def validate_imports(self, code: str) -> list[str]:
        """Return a list of disallowed imports found in *code*.

        Parameters
        ----------
        code : str
            Python source code to scan.

        Returns
        -------
        list[str]
            Module names that are **not** in the allowed whitelist.
            Empty list means the code is safe to run.
        """
        violations: list[str] = []
        for match in _IMPORT_RE.finditer(code):
            module = (match.group(1) or match.group(2)).split(".")[0]
            if module not in self._allowed:
                violations.append(module)
        return violations

    # ── execution engine ────────────────────────────────────────────

    def execute(
        self,
        code: str,
        timeout: int | None = None,
    ) -> SandboxResult:
        """Execute Python code in an isolated subprocess.

        Parameters
        ----------
        code : str
            Python source code to execute.
        timeout : int | None
            Maximum wall-clock seconds.  Falls back to
            ``self._default_timeout`` if ``None``.

        Returns
        -------
        SandboxResult
            Frozen dataclass with ``success``, ``output``, ``error``,
            ``execution_time``, ``timed_out``, and ``return_code``.

        Notes
        -----
        - The code runs via ``subprocess.run([sys.executable, '-c', code])``
          in a **separate process** with no shared state.
        - ``subprocess.TimeoutExpired`` is caught and converted into a
          ``SandboxResult`` with ``timed_out=True``.
        - Import whitelist violations are caught **before** execution
          and reported as an error without spawning a subprocess.
        """
        if timeout is None:
            timeout = self._default_timeout

        # ── pre-flight: empty code ──────────────────────────────────
        if not code.strip():
            return SandboxResult(
                success=False,
                output="",
                error="No code provided.",
                execution_time=0.0,
                timed_out=False,
                return_code=-1,
            )

        # ── pre-flight: import whitelist ────────────────────────────
        violations = self.validate_imports(code)
        if violations:
            return SandboxResult(
                success=False,
                output="",
                error=(
                    f"Import policy violation — disallowed modules: "
                    f"{', '.join(sorted(violations))}. "
                    f"Allowed: {', '.join(sorted(self._allowed))}."
                ),
                execution_time=0.0,
                timed_out=False,
                return_code=-1,
            )

        # ── execute in subprocess ───────────────────────────────────
        t0 = time.perf_counter()
        try:
            proc = subprocess.run(
                [sys.executable, "-c", code],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            elapsed = time.perf_counter() - t0

            stdout = proc.stdout.strip()
            stderr = proc.stderr.strip()
            success = proc.returncode == 0 and not stderr

            return SandboxResult(
                success=success,
                output=stdout,
                error=stderr,
                execution_time=round(elapsed, 4),
                timed_out=False,
                return_code=proc.returncode,
            )

        except subprocess.TimeoutExpired:
            elapsed = time.perf_counter() - t0
            return SandboxResult(
                success=False,
                output="",
                error=f"Execution timed out after {timeout}s.",
                execution_time=round(elapsed, 4),
                timed_out=True,
                return_code=-1,
            )

    # ── extraction + execution shortcut ─────────────────────────────

    def run_from_completion(
        self,
        completion: str,
        timeout: int | None = None,
    ) -> SandboxResult:
        """Extract code from an LLM completion and execute it.

        Convenience method combining :meth:`extract_code` and
        :meth:`execute`.

        Parameters
        ----------
        completion : str
            Raw LLM output containing a markdown code block.
        timeout : int | None
            Execution timeout (seconds).

        Returns
        -------
        SandboxResult
        """
        code = self.extract_code(completion)
        return self.execute(code, timeout=timeout)

    # ── verification logic ──────────────────────────────────────────

    @staticmethod
    def verify_output(
        result: SandboxResult,
        expected_value: str,
        case_sensitive: bool = False,
    ) -> bool:
        """Check whether the sandbox output contains the expected value.

        This is the integration point with the GRPO reward system.
        After the LLM generates a medical calculation and the sandbox
        executes it, this method verifies the numerical / textual
        result against the ground truth.

        Parameters
        ----------
        result : SandboxResult
            The result from a prior :meth:`execute` call.
        expected_value : str
            The expected string to search for in ``result.output``.
        case_sensitive : bool
            Whether comparison is case-sensitive (default ``False``).

        Returns
        -------
        bool
            ``True`` if the execution succeeded *and* the expected
            value is found in the output.
        """
        if not result.success:
            return False

        output = result.output
        expected = expected_value.strip()

        if not case_sensitive:
            output = output.lower()
            expected = expected.lower()

        return expected in output

    # ── repr ────────────────────────────────────────────────────────

    def __repr__(self) -> str:  # noqa: D105
        return (
            f"MedicalCodeSandbox("
            f"allowed_imports={sorted(self._allowed)}, "
            f"default_timeout={self._default_timeout}s)"
        )


# ──────────────────────────────────────────────────────────────────────
# 5.  SELF-TEST
# ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 68)
    print("  BioGemma-Guard — Medical Code Sandbox Self-Test")
    print("=" * 68)

    sandbox = MedicalCodeSandbox()
    passed = 0
    total = 0

    # ── Test 1: Valid dosage calculation ─────────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 1: Valid Dosage Calculation (Pediatric Ibuprofen)")
    print(f"  {'─' * 54}")

    completion_1 = """\
The recommended dose of Ibuprofen for a pediatric patient is 10 mg/kg.

```python
# Pediatric Ibuprofen Dosage Calculator
weight_kg = 25.0          # patient weight
dose_per_kg = 10.0        # mg/kg (standard pediatric dose)
concentration = 100.0     # mg per 5 mL suspension

dose_mg = weight_kg * dose_per_kg
volume_ml = (dose_mg / concentration) * 5.0

print(f"Patient weight: {weight_kg} kg")
print(f"Calculated dose: {dose_mg} mg")
print(f"Volume to administer: {volume_ml} mL")
```

Therefore, a 25 kg child should receive 250 mg (12.5 mL of suspension).
"""

    code_1 = sandbox.extract_code(completion_1)
    result_1 = sandbox.execute(code_1)
    verified_1 = sandbox.verify_output(result_1, "250.0")

    print(f"  Extracted code : {len(code_1)} chars")
    print(f"  Execution      : {result_1}")
    print(f"  Output         :")
    for line in result_1.output.splitlines():
        print(f"    │ {line}")
    print(f"  Verify '250.0' : {'✅ PASS' if verified_1 else '❌ FAIL'}")

    ok_1 = result_1.success and verified_1
    if ok_1:
        passed += 1

    # ── Test 2: Syntax error ────────────────────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 2: Script with Syntax Error")
    print(f"  {'─' * 54}")

    completion_2 = """\
Let me calculate the GCS score:

```python
# Glasgow Coma Scale — intentional syntax error
eye_response = 4
verbal_response = 5
motor_response = 6
gcs_total = eye_response + verbal_response + motor_response
print(f"GCS Total: {gcs_total"  # missing closing brace
```
"""

    code_2 = sandbox.extract_code(completion_2)
    result_2 = sandbox.execute(code_2)

    print(f"  Extracted code : {len(code_2)} chars")
    print(f"  Success        : {result_2.success}  (expected: False)")
    print(f"  Return code    : {result_2.return_code}")
    print(f"  Error preview  : {result_2.error[:80]}…")

    ok_2 = not result_2.success and result_2.return_code != 0
    print(f"  Result         : {'✅ PASS' if ok_2 else '❌ FAIL'}")
    if ok_2:
        passed += 1

    # ── Test 3: Infinite loop (timeout) ─────────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 3: Infinite Loop (Timeout Protection)")
    print(f"  {'─' * 54}")

    completion_3 = """\
```python
# This should be caught by the timeout
while True:
    pass
```
"""

    code_3 = sandbox.extract_code(completion_3)
    result_3 = sandbox.execute(code_3, timeout=2)

    print(f"  Extracted code : {len(code_3)} chars")
    print(f"  Timed out      : {result_3.timed_out}  (expected: True)")
    print(f"  Success        : {result_3.success}  (expected: False)")
    print(f"  Error          : {result_3.error}")
    print(f"  Wall time      : {result_3.execution_time:.2f}s")

    ok_3 = result_3.timed_out and not result_3.success
    print(f"  Result         : {'✅ PASS' if ok_3 else '❌ FAIL'}")
    if ok_3:
        passed += 1

    # ── Test 4: Import policy violation ─────────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 4: Import Policy Violation (os module)")
    print(f"  {'─' * 54}")

    completion_4 = """\
```python
import os
print(os.listdir("/"))
```
"""

    code_4 = sandbox.extract_code(completion_4)
    result_4 = sandbox.execute(code_4)

    print(f"  Extracted code : {len(code_4)} chars")
    print(f"  Success        : {result_4.success}  (expected: False)")
    print(f"  Error          : {result_4.error}")

    ok_4 = not result_4.success and "os" in result_4.error
    print(f"  Result         : {'✅ PASS' if ok_4 else '❌ FAIL'}")
    if ok_4:
        passed += 1

    # ── Test 5: No code block found ─────────────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 5: No Code Block in Completion")
    print(f"  {'─' * 54}")

    completion_5 = "The patient should take 500 mg of Amoxicillin three times daily."
    code_5 = sandbox.extract_code(completion_5)
    result_5 = sandbox.execute(code_5)

    print(f"  Extracted code : '{code_5}' (expected: empty)")
    print(f"  Success        : {result_5.success}  (expected: False)")
    print(f"  Error          : {result_5.error}")

    ok_5 = code_5 == "" and not result_5.success
    print(f"  Result         : {'✅ PASS' if ok_5 else '❌ FAIL'}")
    if ok_5:
        passed += 1

    # ── Test 6: run_from_completion shortcut ────────────────────────
    total += 1
    print(f"\n  {'─' * 54}")
    print("  Test 6: run_from_completion() — NEWS2 Score")
    print(f"  {'─' * 54}")

    completion_6 = """\
Let me calculate the NEWS2 score for this patient.

```python
# NEWS2 (National Early Warning Score 2) Calculator
resp_rate = 22     # breaths/min  -> score 2
spo2 = 94          # %            -> score 1 (Scale 1)
systolic_bp = 100  # mmHg         -> score 1
pulse = 110        # bpm          -> score 2
consciousness = 0  # Alert=0
temperature = 38.5 # °C           -> score 1

# Simplified scoring (real NEWS2 uses lookup tables)
scores = {
    "Respiration rate": 2,
    "SpO2": 1,
    "Systolic BP": 1,
    "Pulse": 2,
    "Consciousness": 0,
    "Temperature": 1,
}

total = sum(scores.values())
print(f"NEWS2 Total: {total}")
if total >= 7:
    print("Clinical risk: HIGH — Urgent response required")
elif total >= 5:
    print("Clinical risk: MEDIUM — Key threshold for urgent response")
else:
    print("Clinical risk: LOW")
```
"""

    result_6 = sandbox.run_from_completion(completion_6)
    verified_6 = sandbox.verify_output(result_6, "NEWS2 Total: 7")

    print(f"  Execution      : {result_6}")
    print(f"  Output         :")
    for line in result_6.output.splitlines():
        print(f"    │ {line}")
    print(f"  Verify 'NEWS2 Total: 7' : {'✅ PASS' if verified_6 else '❌ FAIL'}")

    ok_6 = result_6.success and verified_6
    if ok_6:
        passed += 1

    # ── Summary ─────────────────────────────────────────────────────
    print(f"\n{'─' * 68}")
    print(f"  Results: {passed} passed, {total - passed} failed out of {total} tests")
    status = "✅ All assertions passed" if passed == total else "❌ Some assertions failed"
    print(f"  Overall: {status}")
    print("=" * 68)
